### ISSUE TITLE
Unable to change color and font size

### ISSUE THREAD

**Issue by AlexMayol** [chinchang/screenlog.js#30]
I'm trying to change the color of the font from `lightgreen` to `white` for a better contrast. 

I can change the background color but not the font color:

```
screenLog.init({
	bgColor: 'black',
	color :'white'
});
```

Also, is there an option to change font size? It isn't stated on the API. 

Thanks!

**Comment by chinchang** [comment]
Hi Alex!
Actually the option for color is `logColor` and not `color`. It's my mistake in the API docs. I have fixed it now.
Also, on your request I have added an option for `fontSize` also and also made the default font size same as browser default.
You can get the new change in v0.3.0 👍

**Comment by AlexMayol** [comment]
Thank you, awesome work! 👍
